### PR TITLE
findOne优化

### PR DESCRIPTION
**Pull request by Whislly**
1、直接调用runCommand方法
2、增加"limit": 1参数，限制只返回一条数据

### CODE REVIEW

**Comment by ykxpb** [comment]
这里之前忘记把cursor关闭了，可以顺手改一下 @Whislly 

不手动关闭，会依赖mongo被动超时关闭。

**Comment by ykxpb** [comment]
如果直接用limit(1) 就不需要手动关闭了，会判断是否no more message。

**Comment by ykxpb** [comment]
看文档应该传 -1，

Q: Speaking of "One", where is findOne?
If your driver wishes to offer a findOne method, that is perfectly fine. If you choose to implement findOne, please keep to the naming conventions followed by the FindOptions and keep in mind that certain things don't make sense like limit (which should be -1), tailable, awaitData, etc...

https://github.com/mongodb/specifications/blob/c09f979ad296400552a98c9b784197ec648c2096/source/crud/crud.rst#q--a

**Comment by ykxpb** [comment]
A negative limit is similar to a positive limit but closes the cursor after returning a single [batch](https://www.mongodb.com/docs/manual/tutorial/iterate-a-cursor/#std-label-cursor-batches) of results. As such, with a negative limit, if the limited result set does not fit into a single batch, the number of documents received will be less than the specified limit. By passing a negative limit, the client indicates to the server that it will not ask for a subsequent batch via getMore.

https://www.mongodb.com/docs/manual/reference/method/cursor.limit/#negative-values

**Comment by ykxpb** [comment]
https://www.mongodb.com/docs/manual/reference/command/find/#mongodb-dbcommand-dbcmd.find

看起来是要指定 singleBatch 这个参数才对，根据limit是不是-1来指定，Optional. Determines whether to close the cursor after the first batch. Defaults to false.

**Comment by ykxpb** [comment]
简单点就按照你这个改动，limit改成传singleBatch应该就ok了。

**Comment by Whislly** [comment]
limit不能传-1，传-1会报错（加上singleBatch：true也会报错）：

>  Limit value must be non-negative, but received: -1

文档上也写了limit是 Non-negative integer
[https://www.mongodb.com/docs/manual/reference/command/find/#mongodb-dbcommand-dbcmd.find](https://www.mongodb.com/docs/manual/reference/command/find/#mongodb-dbcommand-dbcmd.find)
<html>
<body>


limit | Non-negative integer | Optional. The maximum number of documents to return. If unspecified, then defaults to no limit. A limit of 0 is equivalent to setting no limit.
-- | -- | --



</body>
</html>

如果不设置limit为1，只传singleBatch:true，返回的cursor.id = 0，但是findOne()不设置条件的时候会返回多条数据
limit传1可以限制只返回一条数据，同时返回的cursor.id = 0，不需要额外的关闭操作，不需要再设置singleBatch:true

**Comment by cloudwu** [comment]
-1 （负数）应该是 mongo 过去的协议标准。负数是说要求自动关闭 cursor 。https://www.mongodb.com/docs/manual/legacy-opcodes/#std-label-wire-op-reply

是不是新协议中已经没有了？

**Comment by Whislly** [comment]
我看了下GO的Mongo驱动Find实现，limit是负数时，设置singleBatch:true, 最后传的limit是正数：
[https://github.com/mongodb/mongo-go-driver/blob/v1.12.0/mongo/collection.go#L1281-L1289](https://github.com/mongodb/mongo-go-driver/blob/v1.12.0/mongo/collection.go#L1281-L1289)
FinOne是设置limit为-1，然后调用Find
[https://github.com/mongodb/mongo-go-driver/blob/v1.12.0/mongo/collection.go#L1403-L1405](https://github.com/mongodb/mongo-go-driver/blob/v1.12.0/mongo/collection.go#L1403-L1405)
所以要改的话也只需要加一个singleBatch:true就可以了

**Comment by ykxpb** [comment]
嗯，加上singleBatch：true就可以了

**Comment by ykxpb** [comment]
其实要不要考虑下支持cursor传-1，类似go这样，因为find():sort():limit(-1) 这样的操作还停常见的。

**Comment by ykxpb** [comment]
> 其实要不要考虑下支持cursor传-1，类似go这样，因为find():sort():limit(-1) 这样的操作还停常见的。

想了下，这种直接传limit(1)也会自动关闭cursor，没什么问题。

**Pull request merged**
